typography_spectrum: 0.1420054438058287
color:
  brandStrength: 0.3715185234323144
  lightness: 0.2875137228984386
  saturation: 0.83726068562828
  rhythmicContrast: 0.6921986385714263
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.5173049573786557
author:
  name: Alan Leung
  email: aleung@raglytravel.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4da1f408-3081-4ef3-9ab6-ef327186d0a4.png
name: Ragly Travel Pty Ltd
navigation:
  - name: Welcome
    url: 'http://www.raglytravel.com.au'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a7eb24b-709f-4bee-af41-e7eb9c0dbcef.png
title: Where would you rather be?
