typography_spectrum: 0.1420054438058287
color:
  brandStrength: 0.3715185234323144
  lightness: 0.2875137228984386
  saturation: 0.83726068562828
  rhythmicContrast: 0.6921986385714263
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.5173049573786557
author:
  name: Alan Leung
  email: aleung@raglytravel.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4ff0a75-6097-40b7-ac3b-3bf509af362d.gif
name: Ragly Travel Pty Ltd
navigation:
  - name: Welcome
    url: 'http://www.raglytravel.com.au'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e9cc3abc-2472-4496-baf5-6cceed7fd2c0.ico
title: Where would you rather be?
